#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Vivado on Tue Apr 18 16:42:54 CDT 2023
=======
# Generated by Vivado on Thu Apr 20 22:40:51 CDT 2023
>>>>>>> main
=======
# Generated by Vivado on Thu Apr 20 22:40:51 CDT 2023
>>>>>>> origin
=======
# Generated by Vivado on Thu Apr 20 22:40:51 CDT 2023
>>>>>>> origin
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj RAMTestbench_vlog.prj"
xvlog --incr --relax -prj RAMTestbench_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
