#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
<<<<<<< HEAD
# Generated by Vivado on Fri Apr 21 16:38:55 CDT 2023
=======
# Generated by Vivado on Sat Apr 22 09:50:42 CDT 2023
>>>>>>> f5fecdc5c6f0209addec253045231f77453660ee
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj InstructionRegisterTestbench_vlog.prj"
xvlog --incr --relax -prj InstructionRegisterTestbench_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
